config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :books
  resources :orders

  get "/about", to: "pages#about"
  get "/search", to: "pages#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id              :bigint           not null, primary key
#  payment_method  :string
#  delivery_method :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Order < ApplicationRecord
  include AASM
  belongs_to :user
  has_many :orders_books
  has_many :books, through: :orders_books
  accepts_nested_attributes_for :orders_books, reject_if: :all_blank, allow_destroy: true
  aasm column: :status do
    state :in_progress, initial: true
    state :finalized
    state :cancelled

    event :delivered do
      transitions from: :in_progress, to: :finalized
    end
    event :cancel do
      transitions from: :in_progress, to: :cancelled
    end
  end
  before_save do |order|
    puts order.status
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    if current_user.admin_role? || current_user.superadmin_role?
      @orders = Order.all
    else
      @orders = Order.where("user_id = ?", current_user.id)
    end
  end
  
  # GET /orders/1 or /orders/1.json
  def show
    #get price, name, quantity
    @acum = 0
    @ticketing = Array.new
    @order.books.each do |book|
      #get quantity
      quantity = OrdersBook.where("order_id= ? AND book_id = ?", @order.id,book.id)
      @ticketing.push([book.name,book.price,quantity[0].quantity])
      @acum = @acum+book.price.to_i * quantity[0].quantity.to_i
    end
    #binding.pry
  end
  
  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    binding.pry
    if !params[:s].nil?
      if params[:s] == "cancel"
        if @order.may_cancel?
          @order.cancel
          flash.now[:notice]= "Order Canceled"
        else
          flash.now[:alert] = "Cannot cancel, Order is: #{@order.status}"
        end

      end
      if params[:s] == "finalize"
        if @order.may_delivered?
          @order.delivered
          flash.now[:notice]= "Order Finalized"
        else
          flash.now[:alert] = "Cannot cancel, Order is: #{@order.status}"
        end
      end
    end
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id,:delivery_method,:payment_method,orders_books_attributes: [:id,:book_id,:quantity,:_destroy])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <h3>Books</h3>
  <div id="BOoks">

    <%= f.simple_fields_for :orders_books do |book| %>
        
          <%= render 'orders_book_fields', f: book %>

      <% end %>
  </div>
    <div class="d-flex justify-content-center mt-4 mb-4">
    <%= link_to_add_association 'Agregar Libro', f, :orders_books,class:"btn btn-success" %>
    </div>
  </div>
  <%= f.input :payment_method, collection: ["Paypal","Tarjeta"] %>
  <%= f.input :delivery_method, collection: ["DHL","FEDEX","UPS"] %>
  <% if current_user.admin_role? || current_user.superadmin_role? %>
    <%= radio_button_tag(:s, "cancel") %>
      <%= label_tag(:s, "cancel") %>
    <%= radio_button_tag(:s, "finalize") %>
      <%= label_tag(:s, "finalize") %>  
  <%end%>
  <div>
    <button id="pricing" type="button", class="btn btn-success">Precio</button>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/_orders_book_fields.html.erb
<div class="nested-fields row  justify-content-center align-items-end" id="test">
  
  <div class="col-6">
    <%= f.input :book_id,label:"Books", collection: Book.all,
    label_html:{class:"form-label"}, input_html:{class:"book"}%>
    <%= f.input :quantity %>
  </div>
  <div class="col-2">
    <%= link_to_remove_association "Eliminar", f, class: "btn btn-danger" %>
  </div>
<%= f.input :_destroy, as: :hidden%>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Payment method</th>
      <th>delivery method</th>
      <th>user</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.payment_method%></td>
        <td><%= order.delivery_method%></td>
        <td><%= order.user.email%></td>
        <td><%= order.status%>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Orden <%= @order.id %></h3>
<h2> Libros en la Orden</h2>
<% @ticketing.each do |book|%>
  <div>
    <%= book[1]%> | <%= book[0] %> x <%= book[2]%> = <%= book[1].to_i * book[2].to_i%>
  </div>
<%end%>
<div>
  Total: <%= @acum%>
</div>
<div>
  Metodo de pago: <%= @order.payment_method%>
</div>
<div>
  Metodo de envio: <%= @order.delivery_method %>
</div>
<div>
  Estado del envio: <%= @order.status %>
</div>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>