config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :books
  resources :orders

  get "/about", to: "pages#about"
  get "/search", to: "pages#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id               :bigint           not null, primary key
#  name             :string
#  author           :string
#  number_of_copies :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Book < ApplicationRecord
  has_one_attached :cover
  has_many :books_categories
  has_many :categories, through: :books_categories
  has_many :orders, through: :orders_books
  has_many :orders_books
  accepts_nested_attributes_for :books_categories, reject_if: :all_blank, allow_destroy: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    @top_seller = Book.where(top_seller: true).limit(5)
    @top_seller.shuffle
  end

  # GET /books/1 or /books/1.json
  def show
    ids = Array.new
    recommendedBooksObjectsID = BooksCategory.where("category_id = ?",@book.categories.first.id)
    recommendedBooksObjectsID.each do |book|
      if book.book_id ==  @book.id
        #asi no tenemos el mismo libro lmao
      else
        ids.push(book.book_id)
      end
    end
    @recommendedBooks = Book.where(id: ids[0...4])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :number_of_copies,:total,:top_seller,:price,:cover,books_categories_attributes: [:id, :category_id,:_destroy])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books_category_fields.html.erb
<div class="nested-fields row  justify-content-center align-items-end">
  
  <div class="col-6">
    <%= f.input :category_id,label:"Category", collection: Category.all,
    label_html:{class:"form-label"}%>
  </div>
  <div class="col-2">
    <%= link_to_remove_association "Eliminar", f, class: "btn btn-danger" %>
  </div>
<%= f.input :_destroy, as: :hidden%>
</div>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :name%>
  <%= f.input :author %>
  <%= f.input :number_of_copies%>
  <%= f.input :price%>
  <%= f.input :cover%>
  <h3>Categories</h3>
  <div id="categories">

    <%= f.simple_fields_for :books_categories do |category| %>
        
          <%= render 'books_category_fields', f: category %>

      <% end %>
  </div>
    <div class="d-flex justify-content-center mt-4 mb-4">
    <%= link_to_add_association 'Agregar Categoria', f, :books_categories,class:"btn btn-success" %>
    </div>
  </div>
  <%= f.button :submit %>
<%end%>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Books</h1>
<% if !@top_seller.blank? %>
  <h3>Top Seller</h3>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th colspan="3"></th>
      <tr>
    </thead>
    <tbody>
      <% @top_seller.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.number_of_copies %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<%end%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Number of copies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.number_of_copies %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Number of copies:</strong>
  <%= @book.number_of_copies %>
</p>
<% if !@recommendedBooks.blank? %>
  <h3>Books like <%= @book.name %></h3>
    <table class="table table-striped table-hover table-dark">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Author</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      <% @recommendedBooks.each do |book|%>
        <tr>
          <td scope="row"><%= book.name %></td>
          <td><%= book.author %></td>
          <td><%= link_to 'Ver el Libro', book, class:"btn btn-info"%></td>
        </tr>
      <%end%>
      </tbody>
    </table>
<%end%>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>